package com.amk.driver;

import java.util.Scanner;

import com.amk.service.EmailService;

public class Driver {
	public static void main(String[] args) {

		System.out.println("                            ***** WELCOME TO EMAIL SERVICE *****");
		System.out.println(" ");
		EmailService emailService = new EmailService();
		Scanner scan = new Scanner(System.in);
		int action=0;
		int departmentChoice=0;
		System.out.println("PRESS 1 TO GENERATE EMAIL AND PASSWORD\nPRESS 2 TO SET NEW PASSWORD\n"
				+ "PRESS 3 TO SET ALTERNATE EMAILID\nPRESS 4 TO CHECK MAIL BOX CAPACITY\nPRESS 0 TO EXIT");
		try {
		action = scan.nextInt();
		}
		catch(Exception e)
		{
			System.out.println("SOMETHING WENT WRONG PROBABLY INPUT MISMATCH...");
			
		}
		scan.nextLine();//consuming the endline character generated by nextInt()
		switch (action) {
		case 1:
			System.out.println("ENTER YOUR FIRST NAME:");
			String firstName = scan.nextLine();
			emailService.setFirstName(firstName);
			System.out.println("ENTER YOUR LAST NAME:");
			String lastName = scan.nextLine();
			emailService.setLastName(lastName);
			System.out.println("ENTER DEPARTMENT\n 1 for sales\n 2 for IT\n 3 for Accounts \n 4 for Hr");
			try {
			departmentChoice = scan.nextInt();
			}
			catch(Exception e)
			{
				System.out.println("SOMETHING WENT WRONG PROBABLY INPUT MISMATCH...");
				scan.close();
				return;
			}
			emailService.setDepartment(departmentChoice);
			System.out.println("YOUR EMAIL ID IS: "+emailService.generateEmail());
			System.out.println("YOUR PASSWORD IS: "+emailService.generatePassword());
			break;
		case 2:
			System.out.println("ENTER YOUR NEW PASSWORD:");
			StringBuffer newPassword = new StringBuffer();
			newPassword.append(scan.nextLine());
			System.out.println(emailService.changePassword(newPassword));
			break;
		case 3:
			System.out.println("ENTER ALTERNATE EMAIL ID:");
			System.out.println(emailService.setAlternateEmailId(scan.nextLine()));
			break;
		case 4:
			System.out.println("MAIL BOX CAPACITY IS: "+emailService.getMailBoxCapacity());
			break;
		default:
			System.exit(0);

		}
      scan.close();
	}

}
